#! /bin/zsh

db_path=$DB_PATH/mongo/data
code_path=$DB_PATH/mongo/code

touch $code_path

code=$(cat $code_path)

if (( ${#code} > 0 ))
then
    echo "MongoDB container might be running with ID ${code}\nIf not:\n\tTry cmd 'rm $code_path'."
    return
fi

code=$(sudo docker run --name mongo -d -v $db_path:/var/lib/mysql -p 27017:27017 mongo)
echo $code > $code_path




