#! /bin/zsh

db_path=$DB_PATH/mysql/data
code_path=$DB_PATH/mysql/code

touch $code_path

code=$(cat $code_path)

if (( ${#code} > 0 ))
then
    echo "MySQL container might be running with ID ${code}\nIf not:\n\tTry cmd 'rm $code_path'."
    return
fi

code=$(sudo docker run --name mysql -d -e MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD -v $db_path:/var/lib/mysql -p 3306:3306 mysql)
echo $code > $code_path




