#! /bin/zsh

touch $MYSQL_DIR/code

code=$(cat $MYSQL_DIR/code)

if (( ${#code} > 0 ))
then
    echo "MySQL container might be running with ID ${code}\nIf not:\n\tTry cmd 'rm $MYSQL_DIR/code'."
    return
fi

code=$(sudo docker run -d -e MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD -v $MYSQL_DIR/data:/var/lib/mysql -p 3306:3306 mysql)
echo $code > $MYSQL_DIR/code




