#! /bin/zsh

db_path=$DB_PATH/mysql/data
code_path=$DB_PATH/mysql/code

touch $code_path
code=$(cat $code_path)

if (( ${#code} == 0 )) then
    echo "There's not mysql container running, or the code file might be deleted by mistake."
    return
fi

code=$(sudo docker stop $code)

rm $code_path








